name: A workflow for my Hello World file
on: push
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: pwd
        run: pwd
      - name: content
        run: ls -l
      - uses: ./action-a
        with:
          MY_NAME: "Spock"
